services:
  postgres:
    image: postgres:${POSGRES_VERSION}
    restart: always
    ports:
      - "${PORTS}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}